import "./globals.css";
import Footer from "./sections/footer";
import Header from "./sections/header";

export const metadata = {
  title: "TheTavern",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
